name: OpenAPI REST
description: OpenAPI support for the REST module.
type: module
package: Web Services
core_version_requirement: ~11
dependencies:
  - drupal:rest
  - openapi:openapi
  - schemata:schemata
  - schemata:schemata_json_schema

# Information added by Vardot on 2025-02-17
version: '2.1.0'
project: 'openapi_rest'
datestamp: 1739790496
