name: OpenAPI REST
description: OpenAPI support for the REST module.
type: module
package: Web Services
core: 8.x
dependencies:
  - openapi:openapi (>=8.x-2.x)
  - schemata:schemata
  - schemata:schemata_json_schema

